version: '2'

services:
  mongo:
    image: mongo:3.6.9
    logging:
      driver: none
    ports:
      - '27017:27017'

  api:
    build: .
    environment:
      MONGO_URL: mongodb://mongo:27017/oxe

    command: 'gunicorn -w 1 -b 0.0.0.0:8080 wsgi:app'
    ports:
      - '8080:8080'